export { default as Home } from "./Home/Home";
export { default as ProductPage } from "./Product/ProductPage";
export { default as ProductList } from "./Product/ProductList"
export { default as Cart } from "./Cart/Cart";
export { default as Error } from "./Error/Error";
export { default as Header } from "./Header/Header";
export { default as Footer } from "./Footer/footer";
export { default as Contact } from "./Contact/Contact";
export { default as About } from "./About/About";
